[tool.poetry]
name = "malwarebytes-premium-trial"
version = "0.1.0"
description = "resets the premium trial for malwarebytes"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "malwarebytes_premium_trial"}]

[tool.poetry.dependencies]
python = "^3.11"
pyuac = "^0.0.3"
pypiwin32 = "^223"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
